export const allNutrients = [
  { label: "Calories", unit: "g", quantity: 0 },
  { label: "Fats", unit: "g", quantity: 0 },
  { label: "Saturated Fats", unit: "g", quantity: 0 },
  { label: "Trans Fats", unit: "g", quantity: 0 },
  { label: "Monounsaturated Fats", unit: "g", quantity: 0 },
  { label: "Polyunsaturated Fats", unit: "g", quantity: 0 },
  { label: "Cholesterol", unit: "mg", quantity: 0 },
  { label: "Sodium", unit: "mg", quantity: 0 },
  { label: "Carbs", unit: "g", quantity: 0 },
  { label: "Fiber", unit: "g", quantity: 0 },
  { label: "Sugars", unit: "g", quantity: 0 },
  { label: "Proteins", unit: "g", quantity: 0 },
  { label: "Vitamin A", unit: "µg", quantity: 0 },
  { label: "Vitamin C", unit: "mg", quantity: 0 },
  { label: "Vitamin B-6", unit: "mg", quantity: 0 },
  { label: "Vitamin B-12", unit: "µg", quantity: 0 },
  { label: "Vitamin D", unit: "µg", quantity: 0 },
  { label: "Vitamin E", unit: "mg", quantity: 0 },
  { label: "Vitamin K", unit: "µg", quantity: 0 },
  { label: "Calcium", unit: "mg", quantity: 0 },
  { label: "Magnesium", unit: "mg", quantity: 0 },
  { label: "Potassium", unit: "mg", quantity: 0 },
  { label: "Iron", unit: "mg", quantity: 0 },
  { label: "Zinc", unit: "mg", quantity: 0 },
  { label: "Phosphorus", unit: "mg", quantity: 0 },
  { label: "Thiamin", unit: "mg", quantity: 0 },
  { label: "Riboflavin", unit: "mg", quantity: 0 },
  { label: "Niacin", unit: "mg", quantity: 0 },
  { label: "Folate", unit: "µg", quantity: 0 },
  { label: "Folic acid", unit: "µg", quantity: 0 },
  { label: "Water", unit: "mg", quantity: 0 },
];

export const unitOfMeasurements = [
  { label: "Serving" },
  { label: "Ounce" },
  { label: "Gram" },
  { label: "Pound" },
  { label: "Kilogram" },
  { label: "Pinch" },
  { label: "Liter" },
  { label: "Fluid ounce" },
  { label: "Gallon" },
  { label: "Pint" },
  { label: "Quart" },
  { label: "Milliliter" },
  { label: "Drop" },
  { label: "Cup" },
  { label: "Tablespoon" },
  { label: "Teaspoon" },
];
